# Generated by Django 3.1.7 on 2021-04-26 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('discord', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(default='00000000', max_length=255, null=True)),
                ('campus', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(max_length=255, null=True)),
                ('program', models.CharField(max_length=255, null=True)),
                ('semester', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('team_type', models.CharField(max_length=255, null=True)),
                ('rank', models.CharField(max_length=255, null=True)),
                ('hacker2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hacker2', to='hacker_api.hacker')),
                ('hacker3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hacker3', to='hacker_api.hacker')),
                ('hacker4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hacker4', to='hacker_api.hacker')),
                ('hacker5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hacker5', to='hacker_api.hacker')),
                ('hackerM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackermaster', to='hacker_api.hacker')),
            ],
        ),
    ]
