# Generated by Django 3.1.7 on 2021-04-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_api', '0002_auto_20210425_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
