version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=et-hack
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: danielcarra/et-hack-compose-test
    build: hack_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hack_backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  angular:
    build: hack-frontend
    image: danielcarra/et-hack-compose-test
    ports:
      - "4000:80"
    depends_on:
      - web
    links:
      - web

